name: build
on: [push]

jobs:
  lwjgl3:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        version: [3.2.2]

    env:
      LWJGL_BUILD_TYPE: release/${{ matrix.version }}
      MACOSX_DEPLOYMENT_TARGET: "10.9"

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - run: echo ${{ runner.os }}
      - name: install dependencies (Ubuntu)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get -y install libgl-dev libgtk-3-dev xorg-dev libglu-dev libgl1-mesa-glx
      - name: setup jdk 8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: clone LWJGL
        run: git clone -b ${{ matrix.version }} --depth 1 https://github.com/LWJGL/lwjgl3.git lwjgl3/lwjgl3
      - name: patch LWJGL
        working-directory: lwjgl3
        run: ../patcher
      - name: setup macOS SDK
        if: ${{ runner.os == 'macOS' }}
        run: |
          sudo xcode-select -switch /Applications/Xcode_10.3.app
          echo "SDKROOT_PROP=-Dsdkroot=$(xcrun -sdk macosx10.14 --show-sdk-path)" >> $GITHUB_ENV
      - name: run build-
        working-directory: lwjgl3/lwjgl3
        run: ant ${{ env.SDKROOT_PROP }} compile-templates clean-generated generate compile
